apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-app-namespace
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
