name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.31.0'  # Vervang door je gewenste kubectl versie

    - name: Set up Kubeconfig
      run: |
        mkdir -p ~/.kube
        echo "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8-tutorial/namespace.yaml
        kubectl apply -f k8-tutorial/nginx-deployment.yaml
        kubectl apply -f k8-tutorial/nginx-service.yaml
        kubectl apply -f k8-tutorial/cronjob.yaml
